weights: /user/a0132471/Files/bit-bucket/pytorch/yolov5-pose/weights/weights/yolov5s6.pt
cfg: ./models/hub/yolov5s6_kpts.yaml
data: ./data/coco_person.yaml
hyp: data/hyp.scratch.yaml
epochs: 100
batch_size: 40
img_size:
- 960
- 960
rect: false
resume: false
nosave: false
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: false
image_weights: false
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
workers: 8
project: runs/train
entity: null
name: exp
exist_ok: false
quad: false
linear_lr: false
label_smoothing: 0.0
upload_dataset: false
bbox_interval: -1
save_period: -1
artifact_alias: latest
kpt_label: false
world_size: 1
global_rank: -1
save_dir: runs/train/exp
total_batch_size: 40
